### ISSUE TITLE
Archivos faltantes.

### ISSUE THREAD

**Issue by MasterJI0000** [javier-es/DownTown-RP#1]
Estaba viendo la GM así de reojo y me di cuenta que faltan archivos, en esté caso del foro el archivo activacion_ig.php si no me equivoco, también falta la CAU, me pregunto si sería posible que publiques los archivos faltantes de la WEB, se lo agradecería un montón ya que su trabajo es algo increíble, veo que le dedico mucho tiempo, muchos códigos modificados a mano, sistemas que no son compatibles aplicadas a Paradise, de verdad, wow, un trabajo 10/10 desde mi punto de vista.

Me gustaría abrir un servidor con está GM si es posible, espero su respuesta.

Gracias de antemano.

**Comment by javier-es** [comment]
Buenas @MasterJI0000.

He creado una carpeta llamada 'web' con los archivos esenciales para el correcto funcionamiento de los servicios web. Tal y como explico, en el caso del CAU es mejor descargar la versión más reciente desde el sitio web oficial y hacer las modificaciones que cada uno crea conveniente.

He decidido no publicar tal cual el foro y el CAU, ya que en el caso del foro es tan sencillo como añadir los archivos de la carpeta /web/foro a la raíz de donde esté instalado el foro SMF (versión 2.1 en adelante), y ya funcionaría.

En cuanto al CAU, es un MantisBT pero con una versión algo antigua, y lo que no quiero es que se abran servidores con un CAU posiblemente vulnerable desde el punto de vista de la seguridad. 

Un saludo y te deseo suerte con el servidor que abrirás.
