### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by Prodigy230** [javier-es/DownTown-RP#10]
Buenas, tengo muchos errores, al comienzo no entendi nada, luego empece a leer un poco mas y ahora sigo en lo mismo jaja, tendrias algun tutorial para idiotas como yo??

**Comment by javier-es** [comment]
Hola @Prodigy230 ,

Debido al tiempo que ha pasado, voy a proceder a cerrar esta incidencia. De todos modos, te recomiendo que te leas las instrucciones de instalación y, en caso de que tengas algún problema con la instalación, abras una nueva incidencia.

Un saludo.
