### ISSUE TITLE
no encuentro los comandos de downtown rp

### ISSUE THREAD

**Issue by ritolte** [javier-es/DownTown-RP#11]
estuve buscando por todos lados los comandos pero no encuentro nada, si me podrian ayudaar lo agradeceria

**Comment by DandyGO** [comment]
yo también necesito los comandos administrativos

**Comment by DandyGO** [comment]
todos los comandos de la GM

**Comment by anonimo-s** [comment]
Yo tambien estaria necesitando todos los comandos del GM

**Comment by javier-es** [comment]
Hola,

Es difícil lo que solicitáis, dado que ha sido un GM que no se hizo nunca con la intención de publicarse, por lo que no se tienen "manuales" por así decirlo. No obstante, he recopilado en un .txt todos los comandos del servidor. La gran mayoría, al ponerlos, imprime la sintaxis por consola por lo que entre la sintaxis y el nombre de comando, se puede inferir qué hace cada comando.

Archivo:

[Listado_de_Comandos_borrador_DTRP.txt](https://github.com/javier-es/DownTown-RP/files/7857252/Listado_de_Comandos_borrador_DTRP.txt)

Destacar que algunos comandos tienen delante dos guiones (--), esto implica que están comentados y que, por tanto, habría que activarlos en sus respectivos resources/sistemas.

Un saludo.
