### ISSUE TITLE
Error en Linux con MySQL

### ISSUE THREAD

**Issue by Pancho-19** [javier-es/DownTown-RP#3]
Me está dando errores con mysql en linux, si me podrías contactar para ver cual es el error más a profundo y ver si me puedes brindar una ayuda, te lo agradecería, mi discord te lo dejo por acá: Pancho#1715

**Comment by javier-es** [comment]
Buenas!

Con el fin de poder ayudarte, me gustaría que realizaras los siguientes pasos:

**1.** Cierra el servidor, si es que lo tienes abierto, y dirígete a la carpeta /mods/deathmatch/logs. Borra todos los archivos que veas ahí.

**2.** Abre el servidor y espera a que se cierre (si se cierra solo), o a que esté abierto completamente (en cuyo caso verás MTA Paradise en la consola)

**3.** Vuelve de nuevo a la carpeta /mods/deathmatch/logs. Verás un archivo llamado server.log. Súbelo a MEGA, aquí a GitHub o a cualquier otra plataforma para subir archivos y pon el enlace.

Así podré ayudarte y además si tu problema lo tienen otros, quedará la solución también de forma pública.

Saludos.

**Comment by Pancho-19** [comment]
https://www.mediafire.com/file/6wqpa30yf82fw77/server.log/file

Ahí tienes el log, gracias por responder!

**Comment by javier-es** [comment]
Vamos por partes, porque he visto algunos errores que son leves y si los dejamos solucionados, mejor.

En negrita es tal cual aparece en el server.log, y después la solución.

**1. [20-06-23 19:09:40] ERROR: Couldn't find file oeste.png for resource customblips
[20-06-23 19:09:40] Loading of resource 'customblips' failed**

Al parecer te falta la imagen oeste.png de la resource customblips, puedes obtenerla desde aquí [https://github.com/javier-es/DownTown-RP/raw/master/resources/customblips/oeste.png](https://github.com/javier-es/DownTown-RP/raw/master/resources/customblips/oeste.png)

**2. [20-06-23 19:09:41] ERROR: Not processing resource 'freecam' as it has duplicates on different paths:
                  Path #1: "resources/freecam"
                  Path #2: "resources/[editor]/freecam"
[20-06-23 19:09:41] ERROR: Not processing resource 'interiors' as it has duplicates on different paths:
                  Path #1: "resources/interiors"
                  Path #2: "resources/[gameplay]/interiors"
[20-06-23 19:09:41] ERROR: Not processing resource 'realdriveby' as it has duplicates on different paths:
                  Path #1: "resources/realdriveby"
                  Path #2: "resources/[gameplay]/realdriveby"
[20-06-23 19:09:41] ERROR: Not processing resource 'runcode' as it has duplicates on different paths:
                  Path #1: "resources/runcode"
                  Path #2: "resources/[admin]/runcode"**

En MTA no puedes tener resources o recursos que se llamen igual, por lo que si quieres usar este GM deberías de eliminar las resources que vienen por defecto en los servidores. Estas son las que se incluyen en las carpetas [editor], [gameplay], [admin], etc. En general, si te descargas el GM desde aquí y usas **únicamente** las resources que están aquí subidas, no deberías tener mayor problema.

**3.[20-06-23 19:09:41] MODULE: File not found - x64/modules/sha.so
[20-06-23 19:09:41] MODULE: File not found - x64/modules/ml_sockets.so
[20-06-23 19:09:41] MODULE: File not found - x64/modules/mta_mysql.so
[20-06-23 19:09:41] MODULE: File not found - x64/modules/sha.so
[20-06-23 19:09:41] MODULE: File not found - x64/modules/ml_sockets.so**

Aquí es donde está el fallo que impide arrancar al servidor. En tu archivo de configuración estás especificando que necesitas los módulos sha.so, ml_sockets.so y mta_mysql.so (además sha.so y ml_sockets.so tratas de cargarlos dos veces)

El único módulo que necesitas para que funcione es el mta_mysql.so, así que elimina o comenta el resto del archivo de configuración mtaserver.conf

En la Wiki de MTA explican más detalladamente cómo configurar el módulo mta_mysql ([https://wiki.multitheftauto.com/wiki/Modules/MTA-MySQL](https://wiki.multitheftauto.com/wiki/Modules/MTA-MySQL)), aunque básicamente son dos pasos:

a) Definir la carga del módulo en mtaserver.conf (esto ya lo tienes hecho)
b) Descargar y colocar el módulo según el sistema operativo y arquitectura. 

En tu caso, tienes un Linux de 64 bits, por lo que tal y como te devuelve el archivo de logs,  debes crear una carpeta llamada x64 (puede ser que no exista), luego otra modules dentro de esta y definitivamente copiar ahí el módulo mta_mysql.so de 64 bits (link: [https://nightly.mtasa.com/files/modules/64/mta_mysql.so](https://nightly.mtasa.com/files/modules/64/mta_mysql.so))

Con eso en orden, el servidor debería de arrancar sin problemas. Pruébalo y nos comentas.

Saludos!

**Comment by Pancho-19** [comment]
Ya me funcionó, gracias por la ayuda compañero!

**Comment by javier-es** [comment]
Perfecto!

Cerraré la incidencia y la dejaré marcada con chincheta, creo que puede ser útil para más personas.

Saludos.

**Comment by anonimo-s** [comment]
Que tal, yo estaria teniendo un problema igual que el compañero pero no pude solucionarlo entonces me gustaria si me podria alguien ayudar con este tema :(
[https://www.mediafire.com/file/e64vg0cwwljn2ip/server.log/file](url)

**Comment by javier-es** [comment]
> Que tal, yo estaría teniendo un problema igual que el compañero pero no pude solucionarlo entonces me gustaría si me podría alguien ayudar con este tema :( a continuación dejo el log server.log [https://www.mediafire.com/file/e64vg0cwwljn2ip/server.log/file](url) También aclaro que eso me esta pasando en el hosting Linux que estoy usando

Hola, si analizamos el fichero server.log encontramos el problema:

`[21-11-15 21:31:41] MODULE: File not found - x64/modules/mta_mysql.dll
[21-11-15 21:31:41] MODULE: File not found - x64/modules/ml_sockets.dll`

El servidor está buscando los módulos mta_mysql.dll y ml_sockets.dll. Esto tendría sentido si el servidor estuviera en Windows, pero mencionas que tu hosting es Linux. Por tanto, deberás de modificar el archivo mtaserver.conf, concretamente el apartado de módulos y sustituir los .dll por .so, tal cual está reflejado en las instrucciones de instalación:
```
    <module src="mta_mysql.so"/> <!-- Linux -->
    <module src="ml_sockets.so"/> <!-- Este módulo en realidad no es necesario pero si quieres ponerlo y lo tienes, adelante -->

```

Lógicamente, deberás tener una carpeta llamada x64, esta a su vez una llamada modules y finalmente poner ahí el módulo mta_mysql.so, el cual puedes obtener desde aquí: [https://nightly.mtasa.com/files/modules/64/mta_mysql.so](https://nightly.mtasa.com/files/modules/64/mta_mysql.so)

Espero haberte servido de ayuda. 

Un saludo.

**Comment by anonimo-s** [comment]
Muchas gracias por responder y disculpa las molestias pero aun sigo teniendo el mismo error no se si estoy haciendo mal las cosas o es algun otro problema dejo mi discord por si me puedes dar una manito por ahi y si puedes y quieres te paso fotos de la instalacion o porsi alguien ve esto y me da una manito ⚡🔱 KS° KODA 👑#5920

**Comment by anonimo-s** [comment]
Al final logre entender el problema y aparentemente ya estaría solucionado agradezco mucho la ayuda
