### ISSUE TITLE
Error en el panel de login

### ISSUE THREAD

**Issue by JuanVillegas420** [javier-es/DownTown-RP#4]
Entro al servidor e intento registrarme para empezar a probar las cosas y sucede este error: "Error en el registro, prueba mas tarde"

Pruebas
![mta-screen_2020-09-29_19-08-05](https://user-images.githubusercontent.com/72324399/95003956-7bdc7200-05bb-11eb-89a2-71e66f9ad753.png)

**Comment by javier-es** [comment]
Buenas!

Por favor, prueba a realizar la instalación en una base de datos nueva, que no haya sido utilizada por el GM de MTA Paradise o derivados de este. Con todo pronóstico, es probable que se deba a que estás reutilizando una base de datos con tablas ya creadas por MTA Paradise, las cuales algunas estructuras no coindicen con las del GM de DownTown.

Quedo a la espera de tus pruebas.

Un saludo.

Javi.

**Comment by javier-es** [comment]
Tras no recibir respuesta por tu parte, procedo a cerrar la incidencia.

Siéntete libre de reabrirla o de abrir una nueva si lo necesitas.

Un saludo.

Javi.
