### ISSUE TITLE
Error radiomp3

### ISSUE THREAD

**Issue by tomaslxc** [javier-es/DownTown-RP#6]
**Cuando ejecuto el comando aparece así:**

Estamos buscando la canción, espera por favor.
Ahora estás escuchando La Contra - Otro día mas (Video oficial)

**y despues este error (solo en F8)**

BASS ERROR 41 in LoadMedia  path:C:\Program Files\MTA San Andreas 1.5\mods\deathmatch\resources\radiomp3\nil  3d:1  loop:0

**Comment by javier-es** [comment]
Buenas,

Es normal que no funcione debido a que el script necesita dos APIs:

- Una que se encargue de la búsqueda de la canción y obtener el ID del vídeo desde YouTube.
- Otra que se encargue de proporcionar el .mp3 al script.

En este caso, la primera API si está funcionando, pero en el caso de la segunda, debes de buscar tú una API pública (ejemplo https://alltubedownload.net/) , o bien montarte una reutilizando el código de https://github.com/Rudloff/alltube

Un saludo.

**Comment by javier-es** [comment]
Tras no recibir respuesta, procedo a cerrar la incidencia.

No dudes en abrir una nueva si lo estimas conveniente @tomaslxc 

Un saludo y felices fiestas.
