### ISSUE TITLE
No me deja crear personajes

### ISSUE THREAD

**Issue by stefanofabi** [javier-es/DownTown-RP#7]
Hola, he instalado todo correctamente. Creo la cuenta e inicio sesión pero a la hora de crear el personaje no me deja escribir.

Alguien más le ocurre lo mismo?

**Comment by javier-es** [comment]
Buenas, siento la tardanza en responder.

Te recomendaría que actualizaras la versión de MTA a nivel de cliente, porque por la fecha de la issue, MTA sacó a producción una versión con problemas a la hora de utilizar las GUI, y puede ser ese el problema que tengas.

@stefanofabi espero que acabes leyendo esto o que hayas solucionado igualmente el problema. Doy un plazo de 7 días para que te pases por aquí, en caso contrario cerraré la issue.

Saludos.
