### ISSUE TITLE
Error modulos y SQL

### ISSUE THREAD

**Issue by ShadowSSW** [javier-es/DownTown-RP#8]
Buenas, quisiera ver si me podrian ayudar, instale todo en mi HOST el cual es lemehost, hize todo como lo explicaste y al final dio error, aqui te dejo el log:

 (La SQL ya la conecte y  aun asi sigue dando error de conexion)

https://www.mediafire.com/file/qn5g6zfsauh2dri/server.log/file

**Comment by javier-es** [comment]
Buenas,

Tal cual se aprecia en los logs aportados, en la última ejecución del servidor:

`[21-03-11 10:21:07] MODULE: Unable to load x64/modules/mta_mysql.so (libmysqlclient.so.16: cannot open shared object file: No such file or directory)`

En la máquina de tu proveedor de host está faltando una biblioteca necesaria, en este caso la libmysqlclient.so.16.

Puedes descargarla de forma oficial desde aquí: https://nightly.mtasa.com/files/libmysqlclient.so.16 y de acuerdo a la documentación, meterla en /usr/lib.

Igualmente, si el sistema es Debian o Ubuntu, puedes proceder a la instalación de forma automática con el comando `apt-get install libmysqlclient16`

Te dejo enlace directo por si necesitas más información de todo lo que te digo: https://wiki.multitheftauto.com/wiki/Installing_and_Running_MTASA_Server_on_GNU_Linux

PD: a mi en estos momentos no me funciona la Wiki de MTA, por lo que aunque supongo que es algo temporal, te dejo enlace igualmente a la versión solo texto cacheada por Google: http://webcache.googleusercontent.com/search?q=cache:52IwZE6K-jEJ:https://wiki.multitheftauto.com/wiki/Installing_and_Running_MTASA_Server_on_GNU_Linux&hl=es&gl=es&strip=1&vwsrc=0

Saludos @ShadowSSW

**Comment by ShadowSSW** [comment]
Mira lo que pasa es que mi host tiene un FTP y no hay ninguna carpeta que se llame usr o lib, que hago? soy nuevo en esto

**Comment by javier-es** [comment]
En tu caso, te recomiendo que te pongas en contacto con tu proveedor de hosting y les pases el enlace a esta incidencia, o explicarles que necesitan instalar la biblioteca libmysqlclient16.

Desde aquí no puedo brindarte más ayuda. 

Saludos!
