### ISSUE TITLE
Problemas al enlazar foro con gm

### ISSUE THREAD

**Issue by Akabuba** [javier-es/DownTown-RP#9]
Hola buenas, llevo unos días intentando sincronizar un foro smf con la gamemode, he seguido los pasos al pie de la letra sin éxito. Hay algún sitio donde haya más documentación sobre ello? Si no fuera así sabrías como hacerlo funcionar? 
Muchas gracias de antemano!

**Comment by Akabuba** [comment]
Al poner /foro me salta un error, pero cuando inició la GM me dice que están conectados sqlforo y sqllogin a la base de datos, pero no tengo nidea de que puede fallar. Conecte el sqlforo a la base de smf versión 2.1 r2  y sqllogin a otra base de datos externa, con el modelo de login.db  y puse las opciones en true.

**Comment by javier-es** [comment]
Buenas @Akabuba 

¿Qué error te sale cuando usas /foro? Ten en cuenta que además de seguir las instrucciones, hay que tener cuidado con algunas funciones.  La función linkAccountForum y resultCreateAccountForum realizan llamadas a https://login.dt-mta.com/activacion_ig.php, https://foro.dt-mta.com/register_ig.php, etcétera. Lógicamente, el register_ig.php debe de estar en al raíz de instalación de tu foro SMF y el activacion_ig.php puede estar ahí o en otra parte, pero debes de respetar las dependencias.

Si no has modificado estos enlaces, ten claro que no te va a funcionar porque estás lanzando las peticiones a URLs que a día de hoy nisiquiera existen.

**Comment by Akabuba** [comment]
Hola Javier, muchas gracias por responder, he modificado los links, como dijistes. Me salta error 404 al poner /foro e introducir los datos. Lo que no tengo nidea es que hacer con login.sql y tampoco tengo nidea para poner /web/login, he probado ha meterlo en la raíz de smf, pero creo que no va ahí porque me saltan errores de PHP. 
Ando un poco perdido como ves, muchas gracias de antemano de nuevo bro

**Comment by javier-es** [comment]
Hola @Akabuba, te cuento.

La idea es que deben de existir dos portales web: uno el foro y otro el servicio de login centralizado. El login.sql es la base de datos que usará el login centralizado, y se decidió poner dicho login centralizado para que se pudieran usar no sólo los servicios de un foro SMF, sino de otros servicios que al final nunca llegaron a desarrollarse.

Me comentas que el error que te da es el 404: eso significa que uno de los fetchRemote o similar, están yendo a la URL que no existe, y de ahí que te devuelva el error 404 de que la página no existe.

Lo que deberías de tener es el foro en un sitio, tipo foro.tudominio.net, y el login en otro, tipo login.tudominio.net. Dentro de la carpeta login tienes el código que debería estar en la raíz del dominio login.tudominio.net. Cabe destacar que todo este código tendrás que revisarlo, puesto que hay que introducir las credenciales de la base de datos del servidor IG por un lado, las credenciales de la base de datos del foro por otro, y las credenciales de la base de datos del propio servicio de login.

Por norma general, el archivo que deberás modificar será el auxiliar.php que se encuentra del directorio login, en concreto las funciones que se encargan de obtener los enlaces a las distintas bases de datos.

Desde aquí puedo ir dándote soporte a medida que te vayas encontrando con algunos problemas que no consigas resolver, pero no puedo dar unas instrucciones tan detalladas como para que se sigan al pie de la letra y todo funcione. Estamos hablando de realizar una interconexión entre tres sistemas diferentes, y esta tarea ya requiere de trabajos manuales y de ciertos conocimientos (sobre todo, en este caso, de PHP)

Un saludo, y quedo a la espera por si necesitas algo más concreto o tienes algún problema preciso.

**Comment by Akabuba** [comment]
Muchas gracias @javier-es ahora lo entiendo todo, he llegado a la conclusión de que en localhost no voy a poder, pero probaré a hacerlo más adelante y te iré diciendo conforme vayan saliendo errores. Estamos en contacto y muchas gracias de nuevo.
